version: '3.9'

services:
  db:
    image: postgres:15
    container_name: dentiapro_db
    env_file:
      - .env  # optional: load DB credentials from an .env file
    environment:
      POSTGRES_DB: dentiapro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dentiapro-net

  web:
    build: .
    container_name: dentiapro_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env  # optional, if you store SECRET_KEY or other vars
    environment:
      # Or define DB credentials right here
      DB_NAME: dentiapro_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"  # Only if you want to access Django directly (e.g. for debug)
    networks:
      - dentiapro-net

  nginx:
    image: nginx:latest
    container_name: dentiapro_nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - dentiapro-net

volumes:
  db_data:

networks:
  dentiapro-net:
    driver: bridge